Adds a demo multi-site scanning script
Automattic/wpscan-examples pull request #2
Opened 2023-06-16 02:52 UTC by jwidavid

Incoming

2023-06-16 10:04 UTC, ArSn commented
I wonder if we should call this something like "multiple sites scanner" instead, just to avoid people confusing it with a [multisite](https://wordpress.org/documentation/article/create-a-network/).

2023-06-16 14:16 UTC, jwidavid commented
> I wonder if we should call this something like "multiple sites scanner" instead, just to avoid people confusing it with a [multisite](https://wordpress.org/documentation/article/create-a-network/).

Yeah, I was wondering about that myself honestly. I just ran with the way it was described in the task, but if you also agree then I'm going to change it.

2023-06-23 11:46 UTC, ArSn requested changes, later dismissed
Works great except for these extra ssh commands. Also, conflict needs to be resolved before merging this.

2023-06-23 11:46 UTC, ArSn commented on multiple-sites-scanner/multiple-sites-scanner.sh
> +	THEMES=$(ssh -i $SSH_KEY_PATH ssh $SSH_CONNECTION "wp theme list --path=$SITE_DIRECTORY --fields=name,version --format=json")
I think these have an extra `ssh` in them for some reason.

```suggestion
	# Run wp-cli commands to get list of plugins, themes, and WP version using SSH key-based authentication
	WP_VERSION=$(ssh -i $SSH_KEY_PATH $SSH_CONNECTION "wp core version --path=$SITE_DIRECTORY")
	PLUGINS=$(ssh -i $SSH_KEY_PATH $SSH_CONNECTION "wp plugin list --path=$SITE_DIRECTORY --fields=name,version --format=json")
	THEMES=$(ssh -i $SSH_KEY_PATH $SSH_CONNECTION "wp theme list --path=$SITE_DIRECTORY --fields=name,version --format=json")
```

2023-06-23 13:10 UTC, bhoop approved these changes
So merged, much wow 👍

2023-06-23 13:10 UTC, merged