Add github action example
Automattic/wpscan-examples pull request #4
Opened 2023-07-10 04:10 UTC by miguelxpn

2023-07-10 22:03 UTC, jwidavid requested changes
Looks and tests good! Just one suggestion based on the instructions provided in the readme.

2023-07-10 22:03 UTC, jwidavid commented on github-action/wpscan.yml
> +          WP_CONTENT_PATH: './wp-content'
```suggestion
          WP_CONTENT_PATH: ${{ secrets.WP_CONTENT_PATH }}
```

2023-07-10 23:38 UTC, miguelxpn commented on github-action/wpscan.yml
> +          WP_CONTENT_PATH: './wp-content'
D'oh! Nice catch! Thanks!

2023-07-11 22:58 UTC, jwidavid approved these changes

2023-07-12 01:23 UTC, merged